name: Mercury-Frontend CI/CD
on: 
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
    
defaults:
      run:
        working-directory: ./MercuryFrontend
jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          # ATTENTION: actions/upload-artifact does not use working-directory !!!
          path: ./MercuryFrontend/dist
 # Deploy Job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./MercuryFrontend/dist/*
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MERCURY_WEBAPP }}
          publish_dir: ./MercuryFrontend/dist
